import { v4 as uuid } from "uuid";

/**
 * Product Database can be added here.
 * You can add products of your wish with different attributes
 * */

export const products = [
  {
    _id: uuid(),
    title: "Dynamic Decision",
    author: "Boris Gelfand",
    price: "1100",
    categoryName: "Book",
    ImageSource: "https://res.cloudinary.com/ducun9wpr/image/upload/v1677648183/ecom-products/41B_Cht2HTL_fj9dgx.jpg",
    starRating: 4.5,
    totalRating: 48,
  },
  {
    _id: uuid(),
    title: "GM Preparation Calculation",
    author: "Jacob Agaard",
    price: "1499",
    categoryName: "Book",
    ImageSource: "https://res.cloudinary.com/ducun9wpr/image/upload/v1677648185/ecom-products/2905_boek_kcac4z.jpg",
    starRating: 5,
    totalRating: 51,
  },
  {
    _id: uuid(),
    title: "Greatest Attacker in Chess",
    author: "Cyrus Lakdawala",
    price: "1699",
    categoryName: "Book",
    ImageSource: "https://res.cloudinary.com/ducun9wpr/image/upload/v1677648184/ecom-products/81vy6TRBHL-1111x1536_xuptw3.jpg",
    starRating: 4,
    totalRating: 44,
  },
  {
    _id: uuid(),
    title: "Round Neck T-shirt",
    author: "ChessBase India",
    price: "650",
    categoryName: "Wearables",
    ImageSource: "https://res.cloudinary.com/ducun9wpr/image/upload/v1677648184/ecom-products/cloth-3_l7higj.jpg",
    starRating: 2,
    totalRating: 26,
  },
  {
    _id: uuid(),
    title: "Zipper Hoodie",
    author: "ChessBase India",
    price: "  1399",
    categoryName: "Wearables",
    ImageSource: "https://res.cloudinary.com/ducun9wpr/image/upload/v1677648184/ecom-products/hoodie-1_jljw9p.jpg",
    starRating: 4,
    totalRating: 43,
  },
  {
    _id: uuid(),
    title: "Chess MySport T-shirt",
    author: "ChessBase India",
    price: "670",
    categoryName: "Wearables",
    ImageSource: "https://res.cloudinary.com/ducun9wpr/image/upload/v1677648183/ecom-products/cloth-2_lugmth.jpg",
    starRating: 2,
    totalRating: 22,
  },
  {
    _id: uuid(),
    title: "Red Bud Rose Wood",
    author: "ChessBase India",
    price: "2500",
    categoryName: "Chess Set",
    ImageSource: "https://res.cloudinary.com/ducun9wpr/image/upload/v1677648184/ecom-products/set-2_klhowv.webp",
    starRating: 3.5,
    totalRating: 38,
  },
  {
    _id: uuid(),
    title: "Ebonized BoxWood",
    author: "ChessBase India",
    price: "3499",
    categoryName: "Chess Set",
    ImageSource: "https://res.cloudinary.com/ducun9wpr/image/upload/v1677648184/ecom-products/set-3_oeqrru.webp",
    starRating: 4,
    totalRating: 42,
  },
  {
    _id: uuid(),
    title: "Stuanton Sheesham Boxwood Set",
    author: "ChessBase India",
    price: "4199",
    categoryName: "Chess Set",
    ImageSource: "https://res.cloudinary.com/ducun9wpr/image/upload/v1677648184/ecom-products/set-2_klhowv.webp",
    starRating: 4.5,
    totalRating: 46,
  },
];
